/**
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.hvl.dat153.forecastfetcher.data;

import no.hvl.dat153.forecastfetcher.data.ForecastTimeInstant;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Parameters which applies to this exact point in time
 **/
@ApiModel(description = "Parameters which applies to this exact point in time")
public class ForecastTimeStepDataInstant {
  
  @SerializedName("details")
  private ForecastTimeInstant details = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ForecastTimeInstant getDetails() {
    return details;
  }
  public void setDetails(ForecastTimeInstant details) {
    this.details = details;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastTimeStepDataInstant forecastTimeStepDataInstant = (ForecastTimeStepDataInstant) o;
    return (this.details == null ? forecastTimeStepDataInstant.details == null : this.details.equals(forecastTimeStepDataInstant.details));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.details == null ? 0: this.details.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastTimeStepDataInstant {\n");
    
    sb.append("  details: ").append(details).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
