/**
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.hvl.dat153.forecastfetcher.data;

import no.hvl.dat153.forecastfetcher.data.ForecastSummary;
import no.hvl.dat153.forecastfetcher.data.ForecastTimePeriod;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Parameters with validity times over twelve hours. Will not exist for all time steps.
 **/
@ApiModel(description = "Parameters with validity times over twelve hours. Will not exist for all time steps.")
public class ForecastTimeStepDataNext12Hours {
  
  @SerializedName("details")
  private ForecastTimePeriod details = null;
  @SerializedName("summary")
  private ForecastSummary summary = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public ForecastTimePeriod getDetails() {
    return details;
  }
  public void setDetails(ForecastTimePeriod details) {
    this.details = details;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public ForecastSummary getSummary() {
    return summary;
  }
  public void setSummary(ForecastSummary summary) {
    this.summary = summary;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastTimeStepDataNext12Hours forecastTimeStepDataNext12Hours = (ForecastTimeStepDataNext12Hours) o;
    return (this.details == null ? forecastTimeStepDataNext12Hours.details == null : this.details.equals(forecastTimeStepDataNext12Hours.details)) &&
        (this.summary == null ? forecastTimeStepDataNext12Hours.summary == null : this.summary.equals(forecastTimeStepDataNext12Hours.summary));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.details == null ? 0: this.details.hashCode());
    result = 31 * result + (this.summary == null ? 0: this.summary.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastTimeStepDataNext12Hours {\n");
    
    sb.append("  details: ").append(details).append("\n");
    sb.append("  summary: ").append(summary).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
