/**
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.hvl.dat153.forecastfetcher.data;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A identifier that sums up the weather condition for this time period, see documentation.
 **/
@ApiModel(description = "A identifier that sums up the weather condition for this time period, see documentation.")
public class WeatherSymbol {
  


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WeatherSymbol weatherSymbol = (WeatherSymbol) o;
    return true;
  }

  @Override
  public int hashCode() {
    int result = 17;
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class WeatherSymbol {\n");
    
    sb.append("}\n");
    return sb.toString();
  }
}
